services:
  autoserial2tcp:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: autoserial2tcp
    restart: unless-stopped
    network_mode: host
    privileged: true
    volumes:
      - ./config.yaml:/config/config.yaml:ro
      - /dev:/dev
    command: ["-v", "-c", "/config/config.yaml"]
